# Baseline recorded from origin/main after upgrading to OTP 28.
# Keep this list strict: new Dialyzer diagnostics must fail CI.
[
  {"lib/mix/tasks/symphony.ctl.ex", "The function call start will not succeed."},
  {"lib/mix/tasks/symphony.project.ex", "The pattern can never match the type true."},
  {"lib/mix/tasks/symphony.project.ex", "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/mix/tasks/symphony.project.ex", "The pattern pattern {'error', _reason@2} can never match the type, because it is covered by previous clauses."},
  {"lib/mix/tasks/symphony.project.ex", "The pattern pattern <__slug@1, __gist_id@1> can never match the type, because it is covered by previous clauses."},
  {"lib/mix/tasks/symphony.tool.ex", "The function call start will not succeed."},
  {"lib/mix/tasks/symphony.tool.ex", "The pattern variable _reason@1 can never match the type, because it is covered by previous clauses."},
  {"lib/mix/tasks/symphony.tracker.ex", "The function call start will not succeed."},
  {"lib/mix/tasks/symphony.tracker.ex", "The pattern variable _reason@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/agent/cli_runner/base.ex", "Type mismatch in call without opaque term in delete."},
  {"lib/symphony_elixir/agent/cli_runner/base.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/symphony_elixir/agent/cli_runner/base.ex", "Type mismatch in call with opaque term in collect_descendants."},
  {"lib/symphony_elixir/agent_execution.ex", "The pattern pattern <__snapshot@1, __covered@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/agent_execution.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/agent_goal.ex", "The pattern can never match the type \n  {:error, :issue_not_found | :project_not_found}\n  | {:ok,\n     %SymphonyElixir.LocalTracker.IssueRecord{\n       :__meta__ => _,\n       :agent_goal => _,\n       :agent_session_id => _,\n       :archived_at => _,\n       :assignee_id => _,\n       :assignee_remote_id => _,\n       :branch_name => _,\n       :comments => _,\n       :completed_at => _,\n       :creator => _,\n       :description => _,\n       :dirty_fields => _,\n       :id => _,\n       :identifier => _,\n       :inserted_at => _,\n       :labels => _,\n       :last_sync_error => _,\n       :last_synced_at => _,\n       :position => _,\n       :priority => _,\n       :project => _,\n       :project_id => _,\n       :pull_requests => _,\n       :remote_id => _,\n       :remote_number => _,\n       :remote_updated_at => _,\n       :remote_url => _,\n       :source_relations => _,\n       :started_at => _,\n       :status => _,\n       :status_id => _,\n       :sync_status => _,\n       :target_relations => _,\n       :title => _,\n       :updated_at => _,\n       :url => _,\n       :worker_id => _\n     }}\n."},
  {"lib/symphony_elixir/agent_runner.ex", "The pattern variable _issue@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/assistant/agent_session.ex", "The test binary() =:= :claude can never evaluate to 'true'."},
  {"lib/symphony_elixir/assistant/agent_session.ex", "The test binary() =:= :codex can never evaluate to 'true'."},
  {"lib/symphony_elixir/assistant/agent_session.ex", "The test binary() =:= nil can never evaluate to 'true'."},
  {"lib/symphony_elixir/assistant/agent_session.ex", "The pattern pattern <_opts@1, __project_slug@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/assistant/agent_session.ex", "The pattern variable __context@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/assistant/agent_session.ex", "The pattern variable __message@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/assistant/agent_session.ex", "The pattern variable __other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/assistant/file_activity_presenter.ex", "The pattern can never match the type \n  %{\n    :id => _,\n    :name => <<_::40, _::size(48)>>,\n    :result => %{<<_::32, _::size(8)>> => nil | binary() | [any()] | number()},\n    :status => <<_::40, _::size(8)>>,\n    :arguments =>\n      binary()\n      | %{<<_::40, _::size(8)>> => nil | binary() | [any(), ...] | non_neg_integer()},\n    :output =>\n      binary()\n      | %{<<_::40, _::size(8)>> => nil | binary() | [any(), ...] | non_neg_integer()}\n  },\n  :arguments | :output,\n  binary() | %{<<_::40, _::size(8)>> => nil | binary() | [any(), ...] | non_neg_integer()}\n."},
  {"lib/symphony_elixir/assistant/history.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir/assistant/history.ex", "The pattern can never match the type {:update, _, nil | map()}."},
  {"lib/symphony_elixir/assistant/issue_documents.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/symphony_elixir/assistant/issue_documents.ex", "The pattern variable __identifier@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/assistant/preview_tools.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir/assistant/side_query.ex", "The pattern can never match the type \n  {:error,\n   :bash_not_found\n   | :response_timeout\n   | <<_::64, _::size(8)>>\n   | {:goal_activation_failed,\n      :empty_objective | :goals_disabled | :invalid_objective | :response_timeout | {_, _}}\n   | {:goal_status_failed, :response_timeout | {_, _}}\n   | {:invalid_thread_payload, _}\n   | {:port_exit, _}\n   | {:response_error, _}\n   | {:invalid_workspace_cwd, :workspace_root, binary()}\n   | {:resume_conversation_failed, _, :response_timeout | {_, _}}\n   | {:invalid_workspace_cwd, :outside_workspace_root, binary(), binary()}}\n."},
  {"lib/symphony_elixir/assistant/side_query.ex", "Function fallback/1 will never be called."},
  {"lib/symphony_elixir/assistant/title_generator.ex", "The pattern can never match the type \n  {:error,\n   :bash_not_found\n   | :response_timeout\n   | <<_::64, _::size(8)>>\n   | {:goal_activation_failed,\n      :empty_objective | :goals_disabled | :invalid_objective | :response_timeout | {_, _}}\n   | {:goal_status_failed, :response_timeout | {_, _}}\n   | {:invalid_thread_payload, _}\n   | {:port_exit, _}\n   | {:response_error, _}\n   | {:invalid_workspace_cwd, :workspace_root, binary()}\n   | {:resume_conversation_failed, _, :response_timeout | {_, _}}\n   | {:invalid_workspace_cwd, :outside_workspace_root, binary(), binary()}}\n."},
  {"lib/symphony_elixir/assistant/tool_executor.ex", "The function call execute will not succeed."},
  {"lib/symphony_elixir/assistant/tool_executor.ex", "The pattern can never match the type {:error, {:invalid_workflow_markdown, binary()}}."},
  {"lib/symphony_elixir/assistant/tool_executor.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/symphony_elixir/assistant/tool_executor.ex", "The pattern can never match the type %SymphonyElixir.LocalTracker.Project{\n  :__meta__ => _,\n  :archived_at => _,\n  :description => _,\n  :id => _,\n  :inserted_at => _,\n  :issues => _,\n  :labels => _,\n  :last_warm_up_run_id => _,\n  :name => _,\n  :repositories => _,\n  :setup => _,\n  :slug => _,\n  :statuses => _,\n  :tracker_config => _,\n  :tracker_kind => _,\n  :updated_at => _,\n  :warm_up_status => _,\n  :warmed_at => _\n}."},
  {"lib/symphony_elixir/assistant/tool_executor.ex", "The pattern can never match the type {:error, binary()}."},
  {"lib/symphony_elixir/assistant/turn_manager.ex", "The pattern can never match the type \n  {:ok,\n   %SymphonyElixir.Assistant.Thread{\n     :__meta__ => _,\n     :agent_kind => _,\n     :id => _,\n     :inserted_at => _,\n     :issue_identifier => _,\n     :messages => _,\n     :metadata => _,\n     :project_slug => _,\n     :provider_bindings => _,\n     :requested_effort => _,\n     :requested_model => _,\n     :resolved_effort => _,\n     :resolved_model => _,\n     :scope => _,\n     :status => _,\n     :title => _,\n     :updated_at => _,\n     :workspace_path => _\n   }}\n."},
  {"lib/symphony_elixir/assistant/turn_timeline.ex", "The @spec for new has an opaque subtype which is violated by the success typing."},
  {"lib/symphony_elixir/claude/coding_agent.ex", "The function call run_turn will not succeed."},
  {"lib/symphony_elixir/claude/coding_agent.ex", "Function acknowledge_goal_inject/4 will never be called."},
  {"lib/symphony_elixir/claude/coding_agent.ex", "Function finalize_goal_inject/8 will never be called."},
  {"lib/symphony_elixir/claude/coding_agent.ex", "Function maybe_transition_native_goal/6 will never be called."},
  {"lib/symphony_elixir/claude/coding_agent.ex", "Function fail_resumed_session/7 will never be called."},
  {"lib/symphony_elixir/claude/coding_agent.ex", "Function report_turn_error/4 will never be called."},
  {"lib/symphony_elixir/claude/coding_agent.ex", "Function issue_context/1 will never be called."},
  {"lib/symphony_elixir/claude/event_humanizer.ex", "The function call t will not succeed."},
  {"lib/symphony_elixir/claude/event_humanizer.ex", "Function humanize_tool_result/1 has no local return."},
  {"lib/symphony_elixir/claude/goal_control.ex", "The pattern variable _unexpected@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/codex/coding_agent.ex", "The pattern can never match the type \n  {:error,\n   :bash_not_found\n   | :response_timeout\n   | <<_::64, _::size(8)>>\n   | {:goal_activation_failed,\n      :empty_objective | :goals_disabled | :invalid_objective | :response_timeout | {_, _}}\n   | {:goal_status_failed, :response_timeout | {_, _}}\n   | {:invalid_thread_payload, _}\n   | {:port_exit, _}\n   | {:response_error, _}\n   | {:invalid_workspace_cwd, :workspace_root, binary()}\n   | {:resume_conversation_failed, _, :response_timeout | {_, _}}\n   | {:invalid_workspace_cwd, :outside_workspace_root, binary(), binary()}}\n."},
  {"lib/symphony_elixir/codex/coding_agent.ex", "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/codex/coding_agent.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/codex/coding_agent.ex", "Function maybe_archive_on_stop/2 will never be called."},
  {"lib/symphony_elixir/codex/coding_agent.ex", "The pattern pattern {'error', _reason@2} can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/codex/coding_agent.ex", "The pattern variable __payload@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/codex/config.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/codex/event_humanizer.ex", "The function call t will not succeed."},
  {"lib/symphony_elixir/codex/event_humanizer.ex", "Function humanize_item_lifecycle/2 has no local return."},
  {"lib/symphony_elixir/codex/event_humanizer.ex", "The pattern can never match the type false."},
  {"lib/symphony_elixir/codex/model_catalog.ex", "The pattern can never match the type {:error, :response_timeout | {:port_exit, _}}."},
  {"lib/symphony_elixir/codex/model_catalog.ex", "Function present_catalog/1 will never be called."},
  {"lib/symphony_elixir/codex/model_catalog.ex", "Function fetch_models/1 will never be called."},
  {"lib/symphony_elixir/codex/model_catalog.ex", "The pattern can never match the type {:error, :bash_not_found | :response_timeout | {:port_exit, _}}."},
  {"lib/symphony_elixir/codex/model_catalog.ex", "The pattern variable _line@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/codex/model_catalog.ex", "Function handle_response_line/4 will never be called."},
  {"lib/symphony_elixir/codex/session_log.ex", "The pattern variable __decoded@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/config.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/config/workflow.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir/config/workflow.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/config/workflow.ex", "The pattern variable __raw@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/cursor/coding_agent.ex", "The function call run_turn will not succeed."},
  {"lib/symphony_elixir/cursor/coding_agent.ex", "The pattern can never match the type {:error, _}."},
  {"lib/symphony_elixir/cursor/coding_agent.ex", "The pattern can never match the type _, %{:input_tokens => _, :output_tokens => _, :total_tokens => _}."},
  {"lib/symphony_elixir/dev_server/instance.ex", "Type mismatch in call without opaque term in resolve_symlink."},
  {"lib/symphony_elixir/dev_server/instance.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/symphony_elixir/dev_server/instance.ex", "Type mismatch in call with opaque term in realpath."},
  {"lib/symphony_elixir/dev_server/instance.ex", "Type mismatch in call with opaque term in resolve_realpath."},
  {"lib/symphony_elixir/dev_server/manager.ex", "The pattern variable __workspace_path@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/dev_server/manager.ex", "The pattern pattern <__ctx@1, __offset@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/dev_server/manager.ex", "Type mismatch in call without opaque term in resolve_symlink."},
  {"lib/symphony_elixir/dev_server/manager.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/symphony_elixir/dev_server/manager.ex", "Type mismatch in call with opaque term in realpath."},
  {"lib/symphony_elixir/dev_server/manager.ex", "Type mismatch in call with opaque term in resolve_realpath."},
  {"lib/symphony_elixir/dev_server/manager.ex", "The pattern variable __message@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/dev_server/port_plan.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir/dev_server/reconciler.ex", "The pattern variable __auto_start_on@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/dev_server/reconciler.ex", "The pattern can never match the type {:error, _}."},
  {"lib/symphony_elixir/dev_server/snapshot.ex", "The pattern pattern <__serve_steps@1, __server@1, __slug@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/evidence/commit_message_generator.ex", "The pattern can never match the type \n  {:error,\n   :bash_not_found\n   | :response_timeout\n   | <<_::64, _::size(8)>>\n   | {:goal_activation_failed,\n      :empty_objective | :goals_disabled | :invalid_objective | :response_timeout | {_, _}}\n   | {:goal_status_failed, :response_timeout | {_, _}}\n   | {:invalid_thread_payload, _}\n   | {:port_exit, _}\n   | {:response_error, _}\n   | {:invalid_workspace_cwd, :workspace_root, binary()}\n   | {:resume_conversation_failed, _, :response_timeout | {_, _}}\n   | {:invalid_workspace_cwd, :outside_workspace_root, binary(), binary()}}\n."},
  {"lib/symphony_elixir/evidence/commits.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/evidence/judge.ex", "The pattern can never match the type \n  {:error,\n   :bash_not_found\n   | :response_timeout\n   | <<_::64, _::size(8)>>\n   | {:goal_activation_failed,\n      :empty_objective | :goals_disabled | :invalid_objective | :response_timeout | {_, _}}\n   | {:goal_status_failed, :response_timeout | {_, _}}\n   | {:invalid_thread_payload, _}\n   | {:port_exit, _}\n   | {:response_error, _}\n   | {:invalid_workspace_cwd, :workspace_root, binary()}\n   | {:resume_conversation_failed, _, :response_timeout | {_, _}}\n   | {:invalid_workspace_cwd, :outside_workspace_root, binary(), binary()}}\n."},
  {"lib/symphony_elixir/evidence/proposer.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir/evidence/remote_artifacts.ex", "The pattern can never match the type {:error, _}."},
  {"lib/symphony_elixir/evidence/remote_artifacts.ex", "Function upload_and_cache/3 will never be called."},
  {"lib/symphony_elixir/evidence/remote_artifacts.ex", "Function cached_ref/2 will never be called."},
  {"lib/symphony_elixir/evidence/remote_artifacts.ex", "Function cache_ref/4 will never be called."},
  {"lib/symphony_elixir/evidence/remote_artifacts.ex", "Function sha256/1 has no local return."},
  {"lib/symphony_elixir/evidence/remote_artifacts.ex", "The function call stream! will not succeed."},
  {"lib/symphony_elixir/evidence/workspace_commit.ex", "The pattern can never match the type binary()."},
  {"lib/symphony_elixir/gateways/router.ex", "The pattern can never match the type \n  {:new_session | :project_pair | :set_agent | :set_mode | :setup | :setup_pair | :stop,\n   %{\n     :agent_kind => <<_::40, _::size(8)>>,\n     :args => [any()],\n     :code => binary(),\n     :mode => <<_::16, _::size(8)>>\n   }},\n  %SymphonyElixir.Gateways.Binding{\n    :__meta__ => _,\n    :account_id => _,\n    :active_issue_identifier => _,\n    :active_kb_page_path => _,\n    :active_kb_repo_slug => _,\n    :active_mode => _,\n    :active_thread => _,\n    :active_thread_id => _,\n    :binding_kind => _,\n    :conversation_id => _,\n    :default_agent_kind => _,\n    :default_mode => _,\n    :id => _,\n    :inserted_at => _,\n    :metadata => _,\n    :parent_conversation_id => _,\n    :project_slug => _,\n    :provider => _,\n    :sender_id => _,\n    :status => _,\n    :thread_id => _,\n    :updated_at => _\n  },\n  %SymphonyElixir.Gateways.InboundMessage{\n    :conversation_kind => <<_::40, _::size(8)>>,\n    _ => _\n  },\n  _\n."},
  {"lib/symphony_elixir/gateways/router.ex", "The function call send_message_to_thread will not succeed."},
  {"lib/symphony_elixir/github/api.ex", "The pattern can never match the type \n  {:error,\n   :missing_github_token\n   | {:github_api_request, _}\n   | {:github_api_status, integer()}\n   | {:rate_limited, map()}}\n."},
  {"lib/symphony_elixir/github/api.ex", "Function rest_has_next_page?/1 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function header_value/2 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function rest_check_runs/4 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function rest_commit_statuses/4 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function normalize_rest_pull_detail/5 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function rest_mergeable/1 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function rest_pr_state/1 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function rest_pipelines/1 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function rest_status_contexts/1 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function rest_checks_state/2 will never be called."},
  {"lib/symphony_elixir/github/api.ex", "Function normalize_lower/1 will never be called."},
  {"lib/symphony_elixir/github/attachment_rewriter.ex", "The pattern variable __basename@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/github/gist.ex", "The pattern can never match the type \n  {:error,\n   :missing_github_token\n   | {:github_api_request, _}\n   | {:github_api_status, integer()}\n   | {:rate_limited, map()}}\n."},
  {"lib/symphony_elixir/github/gist.ex", "The pattern can never match the type \n  {:error,\n   {:github_api_request, _} | {:github_api_status, integer()} | {:rate_limited, map()}}\n."},
  {"lib/symphony_elixir/github/issue_adapter.ex", "The pattern variable __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/github/issue_create_repo.ex", "The pattern variable __project@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/github/pull_requests.ex", "The pattern pattern <__project@1, _identifier@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/github/state_reconciliation.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir/issue_dispatch.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir/issue_dispatch_prep.ex", "The pattern variable __comments@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/knowledge_base/git.ex", "The pattern variable __reason@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/local_tracker/context.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/symphony_elixir/local_tracker/issue_adapter.ex", "The pattern can never match the type \n  {:error,\n   :issue_not_found\n   | :project_not_found\n   | %Ecto.Changeset{\n       :action => atom(),\n       :changes => map(),\n       :constraints => [any()],\n       :data => nil | map(),\n       :empty_values => _,\n       :errors => [any()],\n       :filters => map(),\n       :params => nil | map(),\n       :prepare => [any()],\n       :repo => atom(),\n       :repo_opts => [any()],\n       :required => [any()],\n       :types => map(),\n       :valid? => boolean(),\n       :validations => [any()]\n     }}\n."},
  {"lib/symphony_elixir/local_tracker/projects.ex", "The pattern can never match the type {:error, binary()}."},
  {"lib/symphony_elixir/notion/markdown.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/opencode/model_catalog.ex", "The pattern variable __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/orchestrator.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir/orchestrator.ex", "The pattern pattern <__running_entry@1, __reason@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/orchestrator.ex", "The pattern pattern <_contract_status@1, __bundle@1, __released_units@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/orchestrator.ex", "The pattern variable __comments@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/orchestrator.ex", "The pattern variable __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/orchestrator.ex", "The pattern variable __opts@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/orchestrator/goal_state.ex", "The pattern pattern <__goal@1, __agent_kind@1, _existing@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/project_config.ex", "The pattern pattern <__front_matter@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/project_config.ex", "The pattern variable __front_matter@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/project_config.ex", "The pattern variable __prompt@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/prompt_builder.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/pull_request_merge.ex", "The pattern pattern <__body@1, _method@1, _bypass@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/pull_request_monitor.ex", "The pattern can never match the type %SymphonyElixir.LocalTracker.IssueRecord{\n  :__meta__ => _,\n  :agent_goal => _,\n  :agent_session_id => _,\n  :archived_at => _,\n  :assignee_id => _,\n  :assignee_remote_id => _,\n  :branch_name => _,\n  :comments => _,\n  :completed_at => _,\n  :creator => _,\n  :description => _,\n  :dirty_fields => _,\n  :id => _,\n  :identifier => _,\n  :inserted_at => _,\n  :labels => _,\n  :last_sync_error => _,\n  :last_synced_at => _,\n  :position => _,\n  :priority => _,\n  :project => _,\n  :project_id => _,\n  :pull_requests => _,\n  :remote_id => _,\n  :remote_number => _,\n  :remote_updated_at => _,\n  :remote_url => _,\n  :source_relations => _,\n  :started_at => _,\n  :status => _,\n  :status_id => _,\n  :sync_status => _,\n  :target_relations => _,\n  :title => _,\n  :updated_at => _,\n  :url => _,\n  :worker_id => _\n}."},
  {"lib/symphony_elixir/pull_request_monitor.ex", "The pattern can never match the type \n  {:error,\n   :missing_github_token\n   | {:github_api_request, _}\n   | {:github_api_status, integer()}\n   | {:rate_limited, map()}}\n."},
  {"lib/symphony_elixir/pull_request_monitor/reconciler.ex", "The pattern can never match the type {:error, _}."},
  {"lib/symphony_elixir/recents.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/session_log.ex", "The pattern pattern <_other@1, __opts@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/session_log.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/settings/credentials.ex", "The pattern variable __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/status_dashboard.ex", "The function call t will not succeed."},
  {"lib/symphony_elixir/status_dashboard.ex", "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/tracker/identity.ex", "The pattern can never match the type \n  {:error,\n   :missing_jira_credentials\n   | :missing_jira_viewer_identity\n   | {:jira_api_request, _}\n   | {:jira_api_status, _}}\n."},
  {"lib/symphony_elixir/tracker/identity.ex", "The pattern can never match the type \n  {:error,\n   :missing_linear_viewer_identity\n   | {:linear_api_request, _}\n   | {:linear_api_status, _}\n   | {:linear_graphql_errors, _}}\n."},
  {"lib/symphony_elixir/tracker/project_sessions.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir/worker_failure.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir/workpad/execution_bundle/validator.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/symphony_elixir_web/channels/assistant_channel.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/channels/assistant_channel.ex", "The pattern can never match the type \n  {:ok,\n   %SymphonyElixir.Assistant.Thread{\n     :__meta__ => _,\n     :agent_kind => _,\n     :id => _,\n     :inserted_at => _,\n     :issue_identifier => _,\n     :messages => _,\n     :metadata => _,\n     :project_slug => _,\n     :provider_bindings => _,\n     :requested_effort => _,\n     :requested_model => _,\n     :resolved_effort => _,\n     :resolved_model => _,\n     :scope => _,\n     :status => _,\n     :title => _,\n     :updated_at => _,\n     :workspace_path => _\n   }}\n."},
  {"lib/symphony_elixir_web/channels/assistant_channel.ex", "Function start_tracked_turn/6 has no local return."},
  {"lib/symphony_elixir_web/channels/assistant_channel.ex", "The pattern variable __context@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/channels/assistant_channel.ex", "The pattern pattern <_socket@1, __payload@1> can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/channels/assistant_channel.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir_web/channels/assistant_channel.ex", "The pattern variable __summary@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/channels/assistant_channel.ex", "The pattern can never match the type {:error, _}."},
  {"lib/symphony_elixir_web/channels/assistant_channel.ex", "The pattern variable __payload@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/channels/session_log_channel.ex", "The pattern variable __id@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/channels/session_log_channel.ex", "The function call issue_agent_kind will not succeed."},
  {"lib/symphony_elixir_web/channels/session_log_channel.ex", "The pattern variable _reason@1 can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/controllers/tracker/assistant_controller.ex", "The function call render will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/assistant_controller.ex", "The pattern can never match the type {:error, :attachment_not_found}."},
  {"lib/symphony_elixir_web/controllers/tracker/assistant_controller.ex", "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/controllers/tracker/assistant_thread_controller.ex", "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/controllers/tracker/assistant_thread_controller.ex", "The function call render will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/dev_server_controller.ex", "The pattern can never match the type {:error, :invalid_server_id}."},
  {"lib/symphony_elixir_web/controllers/tracker/dev_server_controller.ex", "The pattern pattern {'error', __reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/controllers/tracker/issue_controller.ex", "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/symphony_elixir_web/controllers/tracker/issue_controller.ex", "The pattern can never match the type {:error, :invalid_action}."},
  {"lib/symphony_elixir_web/controllers/tracker/issue_controller.ex", "The function call resume will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/issue_controller.ex", "The function call hard_reset will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/issue_controller.ex", "The function call stop will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/issue_controller.ex", "The function call continue_work will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/issue_controller.ex", "The test [binary(), ...] == [] can never evaluate to 'true'."},
  {"lib/symphony_elixir_web/controllers/tracker/knowledge_base_controller.ex", "The function call render will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/knowledge_base_controller.ex", "The pattern can never match the type {:ok, %{:connected => boolean(), :tree => [map()]}}."},
  {"lib/symphony_elixir_web/controllers/tracker/project_controller.ex", "The function call state_for will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/project_controller.ex", "The pattern can never match the type {:error, binary()}."},
  {"lib/symphony_elixir_web/controllers/tracker/template_controller.ex", "The function call render will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/terminal_tab_controller.ex", "The pattern can never match the type {:ok, [map()]}."},
  {"lib/symphony_elixir_web/controllers/tracker/workspace_provision_controller.ex", "The function call render will not succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/worktree_inventory_controller.ex", "The guard clause can never succeed."},
  {"lib/symphony_elixir_web/controllers/tracker/worktree_inventory_controller.ex", "Function force_json_format/2 will never be called."},
  {"lib/symphony_elixir_web/tracker_errors.ex", "The function call render will not succeed."},
]
